### ISSUE TITLE
z-index of footer prevents closing of new-question sidebar

### ISSUE THREAD

**Issue by cookiengineer** [aswdesign/hypersurface#1]
[Screenshot](https://i.imgur.com/N4CrhdF.png)

If you are in the `/feed` view and you click on "New Question", the sidebar can't be closed again because the z-index of the `footer` element is higher than the sidebar.

The footer has a `top: 90%` margin, which is bad. Better is something like `bottom: 0%`.

**Required CSS Fixes**:

- remove `footer` CSS rule `top: 90%`
- add `footer` CSS rule `bottom: 0%`
- move [this CSS class](https://github.com/aswdesign/hypersurface/blob/f779f65e1fb107cbf34e356aadf1bbf044a7ecbd/src/components/Add.vue#L274) to position `top: 0%, right: 0%, bottom: 0%, left: auto; z-index: 2`
- remove `margin-right, transform, left` rules from previous `.add` class

**Comment by aswdesign** [comment]
Changed the footer to `bottom` and ended up just removing the z-index completely. The z-index was placed there to prevent overlapping with the footer in the `/tour` view if it was accessed within the `/info` view. It was unnecessary. Sidebars close as expected now.
